import type { Metadata } from "next";
import Provider from "./Provider";

export const metadata: Metadata = {
	title: "Expense Tracker",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Provider>{children}</Provider>
		</html>
	);
}
